### ISSUE TITLE
Export favorite albums

### ISSUE THREAD

**Issue by bndw** [iangilman/rdio-exodus#2]
Hi, 

I would like to use [your tool](http://iangilman.com/rdio-exodus/export-favorite-albums/) for exporting my Rdio favorites, but since it requires me to **login with my Rdio account**, I'd like to review the source to ensure my data is not being used inappropriately.

Is this possible?

Thanks!

**Comment by iangilman** [comment]
Of course! Here it is: 

https://github.com/iangilman/rdio-exodus/blob/master/export-favorite-albums/js/main.js

It also uses this library: 

https://github.com/rdio/jsapi-examples/tree/master/utils

...and of course the Rdio JavaScript API. 

Note that the app itself doesn't take your credentials; the logging in is handled through Rdio's OAuth process, so the app doesn't know your password. Of course it still has access to make changes to your account, so I appreciate your concern. Once you've exported, you can revoke access to the app here: 

http://www.rdio.com/settings/external/

I hope that answers your questions!

**Comment by bndw** [comment]
@iangilman Thanks for the quick and thorough response!

Thanks for the useful tool and RIP Rdio!
